"""Render the manifest-backed human catalog for the standards repository."""

from __future__ import annotations

import json
from collections import Counter
from collections.abc import Mapping
from typing import cast

from project_standards.adopt.manifest import ArtifactProvenance
from project_standards.package_contract.repository import PackageRepository
from project_standards.standards_graph.model import StandardNode, StandardsGraph


def _cell(values: list[str]) -> str:
    return ", ".join(f"`{value}`" for value in values) if values else "—"


def _registry_defaults(graph: StandardsGraph) -> dict[str, str]:
    path = graph.root / "src" / "project_standards" / "schemas" / "registry.json"
    if not path.is_file():
        return {}
    raw = cast("object", json.loads(path.read_text(encoding="utf-8")))
    if not isinstance(raw, dict):
        return {}
    defaults: dict[str, str] = {}
    for key, value in cast("dict[object, object]", raw).items():
        if not isinstance(key, str) or not isinstance(value, dict):
            continue
        value_map = cast("dict[object, object]", value)
        default = value_map.get("default")
        if isinstance(default, str):
            defaults[key] = default
    contract_defaults: dict[str, str] = {}
    for node in graph.standards:
        candidates = [node.standard_id.replace("-", "_")]
        candidates.extend(
            namespace.rsplit(".", 1)[-1] for namespace in node.manifest.config.namespaces
        )
        for candidate in candidates:
            if candidate in defaults:
                contract_defaults[node.standard_id] = defaults[candidate]
                break
    return contract_defaults


def _artifact_summary(node: StandardNode) -> tuple[str, str, str]:
    manifest = node.artifact_manifest
    if manifest is None:
        return "0", "—", "—"
    counts = Counter(artifact.provenance.value for artifact in manifest.artifacts)
    provenance = ", ".join(f"{name}: {counts[name]}" for name in sorted(counts))
    skills = sorted(
        artifact.dest
        for artifact in manifest.artifacts
        if artifact.dest is not None
        and artifact.source is not None
        and (
            artifact.source.startswith("skills/")
            or (
                artifact.provenance is ArtifactProvenance.GENERATED
                and "/skills/" in artifact.source
            )
        )
    )
    return str(len(manifest.artifacts)), provenance, _cell(skills)


def load_contract_defaults(graph: StandardsGraph) -> dict[str, str]:
    """Load consumer contract defaults for catalog rendering."""
    return _registry_defaults(graph)


def _render_package_catalog(
    repository: PackageRepository,
    *,
    standards_link_prefix: str,
) -> str:
    """Render human-facing catalog facts exclusively from validated V2 packages."""
    if repository.catalog is None:
        raise ValueError("V2 standards catalog requires one loaded catalog source")
    roles = {(entry.id, entry.version.value): entry.role for entry in repository.catalog.packages}
    link_prefix = standards_link_prefix.rstrip("/")
    lines = [
        "<!-- Generated by `project-standards standards render-catalog`; do not edit. -->",
        "",
        "# Standards Catalog",
        "",
        "Validated V2 family, payload, channel, relationship, resource, provider, and output facts.",
        "",
        "## Standards index",
        "",
        "| Standard | Status | Package | Role | Availability | Resources | Providers | Outputs |",
        "| --- | --- | --- | --- | --- | ---: | ---: | ---: |",
    ]
    for family in repository.families:
        standard_id = family.manifest.standard.id
        readme_link = (
            f"{link_prefix}/{standard_id}/README.md" if link_prefix else f"{standard_id}/README.md"
        )
        for loaded in family.payloads:
            payload = loaded.manifest
            version = payload.payload.version.value
            role = roles.get((standard_id, version))
            role_text = role.value if role is not None else "unadvertised"
            lines.append(
                f"| [`{standard_id}`]({readme_link}) | {family.manifest.standard.status.value} | "
                f"{version} | {role_text} | {payload.payload.availability.value} | "
                f"{len(payload.resources)} | {len(payload.providers)} | "
                f"{len(payload.artifacts) + len(payload.contributions)} |"
            )

    lines.extend(
        [
            "",
            "## Capabilities",
            "",
            "| Package | Provides | Consumes platform |",
            "| --- | --- | --- |",
        ]
    )
    for family in repository.families:
        for loaded in family.payloads:
            payload = loaded.manifest
            package = f"{payload.payload.standard}@{payload.payload.version.value}"
            lines.append(
                f"| `{package}` | {_cell(payload.capabilities.provides)} | "
                f"{_cell(payload.capabilities.consumes_platform)} |"
            )

    lines.extend(
        [
            "",
            "## Relationship catalog",
            "",
            "| Package | Relationship | Target |",
            "| --- | --- | --- |",
        ]
    )
    relation_rows = 0
    for family in repository.families:
        for loaded in family.payloads:
            payload = loaded.manifest
            package = f"{payload.payload.standard}@{payload.payload.version.value}"
            for relation, targets in (
                ("companion", payload.relations.companions),
                ("extends", payload.relations.extends),
                ("conflicts", payload.relations.conflicts),
            ):
                for target in targets:
                    lines.append(f"| `{package}` | {relation} | `{target}` |")
                    relation_rows += 1
    if relation_rows == 0:
        lines.append("| — | — | — |")

    lines.extend(
        [
            "",
            "## Resources",
            "",
            "| Package | Resource | Role | URI | Path |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for family in repository.families:
        for loaded in family.payloads:
            payload = loaded.manifest
            standard_id = payload.payload.standard
            version = payload.payload.version.value
            package = f"{standard_id}@{version}"
            for resource in payload.resources:
                uri = f"standards://{standard_id}/{version}/{resource.id}"
                lines.append(
                    f"| `{package}` | `{resource.id}` | `{resource.role}` | "
                    f"`{uri}` | `{resource.path.original}` |"
                )

    lines.extend(
        [
            "",
            "## Providers",
            "",
            "| Package | Provider | Operation | Phase | Effect | Entrypoint |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    provider_rows = 0
    for family in repository.families:
        for loaded in family.payloads:
            payload = loaded.manifest
            package = f"{payload.payload.standard}@{payload.payload.version.value}"
            for provider in payload.providers:
                lines.append(
                    f"| `{package}` | `{provider.id}` | `{provider.operation.value}` | "
                    f"`{provider.phase.value}` | `{provider.effect.value}` | "
                    f"{f'`{provider.entrypoint}`' if provider.entrypoint else '—'} |"
                )
                provider_rows += 1
    if provider_rows == 0:
        lines.append("| — | — | — | — | — | — |")

    lines.extend(
        [
            "",
            "## Managed outputs",
            "",
            "| Package | Kind | Identity | Target | Policy | Adapter / scope |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    output_rows = 0
    for family in repository.families:
        for loaded in family.payloads:
            payload = loaded.manifest
            package = f"{payload.payload.standard}@{payload.payload.version.value}"
            for artifact in payload.artifacts:
                lines.append(
                    f"| `{package}` | artifact | `{artifact.id}` | `{artifact.target.original}` | "
                    f"`{artifact.policy.value}` | whole-file |"
                )
                output_rows += 1
            for contribution in payload.contributions:
                escaped_scope = contribution.scope.replace("|", "\\|")
                lines.append(
                    f"| `{package}` | contribution | `{contribution.id}` | "
                    f"`{contribution.target.original}` | `{contribution.policy.value}` | "
                    f"`{contribution.adapter.value}` / `{escaped_scope}` |"
                )
                output_rows += 1
    if output_rows == 0:
        lines.append("| — | — | — | — | — | — |")
    return "\n".join(lines) + "\n"


def render_catalog(
    graph: StandardsGraph,
    *,
    contract_defaults: Mapping[str, str] | None = None,
    blocked_standard_ids: frozenset[str] = frozenset(),
    standards_link_prefix: str = "",
) -> str:
    """Return deterministic Markdown from graph data and explicit render inputs."""
    if graph.package_repository is not None:
        return _render_package_catalog(
            graph.package_repository,
            standards_link_prefix=standards_link_prefix,
        )
    defaults = contract_defaults or {}
    lines = [
        "<!-- Generated by `project-standards standards render-catalog`; do not edit. -->",
        "",
        "# Standards Catalog",
        "",
        "Manifest-derived package, relationship, resource, provider, and artifact facts.",
        "",
        "## Standards index",
        "",
        "| Standard | Status | Adoption | Package version | Contract default | Config namespaces | Artifacts | Readiness |",
        "| --- | --- | --- | --- | --- | --- | ---: | --- |",
    ]
    for node in graph.standards:
        manifest = node.manifest
        artifact_count, _, _ = _artifact_summary(node)
        versions = ", ".join(manifest.versions.supported)
        link_prefix = standards_link_prefix.rstrip("/")
        readme_link = (
            f"{link_prefix}/{node.standard_id}/README.md"
            if link_prefix
            else f"{node.standard_id}/README.md"
        )
        lines.append(
            f"| [`{node.standard_id}`]({readme_link}) | "
            f"{manifest.standard.status.value} | {manifest.standard.adoption.value} | "
            f"{manifest.versions.latest} (supported: {versions}) | "
            f"{defaults.get(node.standard_id, '—')} | {_cell(manifest.config.namespaces)} | "
            f"{artifact_count} | "
            f"{'blocked' if node.standard_id in blocked_standard_ids else 'ready'} |"
        )

    lines.extend(
        [
            "",
            "## Capabilities",
            "",
            "| Standard | Provides | Consumes platform |",
            "| --- | --- | --- |",
        ]
    )
    for node in graph.standards:
        lines.append(
            f"| `{node.standard_id}` | {_cell(node.manifest.capabilities.provides)} | "
            f"{_cell(node.manifest.capabilities.consumes_platform)} |"
        )

    lines.extend(
        [
            "",
            "## Relationship catalog",
            "",
            "Standards are independent unless an edge appears below.",
            "",
            "| Source | Relationship | Target |",
            "| --- | --- | --- |",
        ]
    )
    relation_rows = 0
    for node in graph.standards:
        for relation, targets in (
            ("companion", node.manifest.relations.companions),
            ("extends", node.manifest.relations.extends),
            ("conflicts", node.manifest.relations.conflicts),
        ):
            for target in sorted(targets):
                lines.append(f"| `{node.standard_id}` | {relation} | `{target}` |")
                relation_rows += 1
    if relation_rows == 0:
        lines.append("| — | — | — |")

    lines.extend(
        [
            "",
            "## Resources",
            "",
            "| Standard | Resource | URI | Path |",
            "| --- | --- | --- | --- |",
        ]
    )
    for node in graph.standards:
        for resource_id, path in sorted(node.manifest.resources.as_dict().items()):
            uri = f"standards://{node.standard_id}/{resource_id}"
            lines.append(f"| `{node.standard_id}` | `{resource_id}` | `{uri}` | `{path}` |")

    lines.extend(
        [
            "",
            "## Providers",
            "",
            "| Standard | Operation | Kind | Entrypoint | Optional |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for node in graph.standards:
        for provider in node.manifest.providers:
            lines.append(
                f"| `{node.standard_id}` | `{provider.operation.value}` | {provider.kind.value} | "
                f"{f'`{provider.entrypoint}`' if provider.entrypoint else '—'} | "
                f"{'yes' if provider.optional else 'no'} |"
            )

    lines.extend(
        [
            "",
            "## Artifact provenance",
            "",
            "| Standard | Artifact manifest | Count | Provenance | Repo-local skills |",
            "| --- | --- | ---: | --- | --- |",
        ]
    )
    for node in graph.standards:
        count, provenance, skills = _artifact_summary(node)
        artifact_path = (
            f"`{node.manifest.artifacts.manifest}`" if node.manifest.artifacts is not None else "—"
        )
        lines.append(
            f"| `{node.standard_id}` | {artifact_path} | {count} | {provenance} | {skills} |"
        )
    return "\n".join(lines) + "\n"
