"""Render, verify, and migrate Markdown Tooling from immutable snapshots."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from typing import cast


def _table(value: object, *, name: str) -> Mapping[str, object]:
    if not isinstance(value, Mapping):
        raise ValueError(f"{name} must be an object")
    return cast("Mapping[str, object]", value)


def _optional_table(value: object) -> Mapping[str, object]:
    return (
        cast("Mapping[str, object]", value)
        if isinstance(value, Mapping)
        else cast("Mapping[str, object]", {})
    )


def _sequence(value: object, *, name: str) -> Sequence[object]:
    if not isinstance(value, Sequence) or isinstance(value, str | bytes):
        raise ValueError(f"{name} must be an array")
    return cast("Sequence[object]", value)


def _config(request: Mapping[str, object]) -> Mapping[str, object]:
    return _table(request.get("config"), name="config")


def _ci(config: Mapping[str, object]) -> Mapping[str, object]:
    return _table(config.get("ci"), name="config.ci")


def _automatic(config: Mapping[str, object], tool: str) -> bool:
    caller = f"{tool}_caller"
    return config.get(tool) is True and _ci(config).get(caller) is True


def _triggers(automatic: bool) -> list[str]:
    if automatic:
        return [
            "on:",
            "  pull_request:",
            "  push:",
            "    branches:",
            "      - main",
            "  workflow_dispatch:",
        ]
    return ["on:", "  workflow_dispatch:"]


def _glob(value: object, *, name: str, role: str) -> str:
    if (
        not isinstance(value, str)
        or not value
        or value.startswith("!")
        or value[0].isspace()
        or value[-1].isspace()
        or "`" in value
        or any(ord(character) < 0x20 or ord(character) == 0x7F for character in value)
        or any(character in "\u0085\u2028\u2029" for character in value)
    ):
        raise ValueError(f"{name} must contain a safe {role} glob")
    return value


def _globs(config: Mapping[str, object], key: str) -> list[str]:
    raw = _sequence(config.get(key), name=f"config.{key}")
    return [_glob(value, name=f"config.{key}", role="include") for value in raw]


def _exclusion_globs(config: Mapping[str, object], tool: str) -> list[str]:
    exclusions = _sequence(config.get("exclusions"), name="config.exclusions")
    result: list[str] = []
    for raw in exclusions:
        exclusion = _table(raw, name="config.exclusions item")
        applies_to = exclusion.get("applies_to")
        glob = exclusion.get("glob")
        if applies_to in {tool, "both"}:
            result.append(
                _glob(
                    glob,
                    name="config.exclusions item",
                    role="exclusion",
                )
            )
    return sorted(result, key=str.encode)


def _yaml_scalar(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


# Issue #63: the format path reaches Prettier through `--ignore-path .gitignore`,
# so generated trees never enter it, while the lint path passes bare CLI globs to
# markdownlint-cli2, which traverses dot directories and `node_modules` (verified
# against the pinned markdownlint-cli2 0.23.2: `**/*.md` selects `.venv/**` and
# `.pytest_cache/**`). markdownlint-cli2 0.23.2 has no `--gitignore` flag — the
# `gitignore` switch is a `.markdownlint-cli2.*` runner-config key, and this
# package deliberately ships only the rule set `.markdownlint.json` — so parity
# is restored with negative CLI globs instead of a second managed config file.
# Every entry is generated by a tool this catalog itself selects; ambiguous
# build outputs (`build/`, `dist/`) stay a consumer `exclusions` decision.
_DEFAULT_LINT_EXCLUSIONS = (
    ".pytest_cache/**",  # pytest cache, ships its own README.md
    ".ruff_cache/**",  # Ruff cache (Python Tooling)
    ".venv/**",  # uv-managed environment (Python Tooling)
    "node_modules/**",  # npm install for this package's own pinned Node tools
)


def _default_lint_exclusions(config: Mapping[str, object], configured: Sequence[str]) -> list[str]:
    """Return the generated-directory exclusions this render adds, if any.

    Opting out is `lint_generated_exclusions = false`, which restores the exact
    1.9 rendering. Negative globs must trail the positive ones because
    markdownlint-cli2 resolves its glob list in order, so a consumer that needs
    one of these trees linted cannot re-include it with a later pattern.
    """
    if config.get("lint_generated_exclusions") is False:
        return []
    already = set(configured)
    return [value for value in _DEFAULT_LINT_EXCLUSIONS if value not in already]


# Corpus ownership, one place for the whole payload.
#
# `markdown_globs` and `config_globs` are the only sources of Prettier's corpus,
# and `markdown_globs` plus the lint exclusions are the only sources of
# markdownlint's. Every consumer of a corpus -- the two managed caller workflows
# and the local commands rendered into the instruction blocks -- goes through the
# matching selection function below, because issue #88 was exactly the drift that
# appears when the CI scope and the documented local scope are computed
# independently: the caller passed the declared globs while the guide printed a
# bare `.`.
#
# Adding a third glob option to express a local-only scope was rejected. It would
# make "the declared corpus" ambiguous, which is the condition that produced #88,
# and neither issue #88 nor issue #114 asks for a scope CI does not already have.
# A consumer narrows the corpus through the existing options or through a typed
# `exclusions` record.


def _format_selection(config: Mapping[str, object]) -> list[str]:
    """Return Prettier's declared corpus: `markdown_globs` then `config_globs`.

    Positives only. The managed caller workflow carries typed exclusions on a
    separate `exclusions` input, which the reusable job turns into an
    `--ignore-path` file, so widening this list would double-apply them there.
    """
    return [*_globs(config, "markdown_globs"), *_globs(config, "config_globs")]


def _format_local_selection(config: Mapping[str, object]) -> list[str]:
    """Return Prettier's local corpus: the declared globs, then every format negation.

    A locally run command has no second channel. The caller workflow can hand
    Prettier an ignore file because it builds one; a consumer following the guide
    would have to author one by hand, which is exactly the step issue #88 says the
    guide must stop requiring. Folding `format`/`both` exclusions into the same
    selection makes the local scope equal the reconciled scope — the declared
    surface minus its typed exclusions — with no new option.

    Only the Git-routed form can consume this. Prettier's CLI has no negative
    pattern, so the fallback still needs `--ignore-path`; `_local_format_commands`
    keeps that split explicit.
    """
    selection = _format_selection(config)
    selection.extend(f"!{value}" for value in _exclusion_globs(config, "format"))
    return selection


def _lint_selection(config: Mapping[str, object]) -> list[str]:
    """Return markdownlint's ordered corpus: positive globs, then every negation.

    Order is part of the contract, not presentation: markdownlint-cli2 resolves
    its glob list in sequence, so a negation placed before a positive glob would
    be re-included by it.
    """
    globs = _globs(config, "markdown_globs")
    configured = _exclusion_globs(config, "lint")
    globs.extend(f"!{value}" for value in _default_lint_exclusions(config, configured))
    globs.extend(f"!{value}" for value in configured)
    return globs


def _prettier_print_width(resources: Mapping[str, bytes]) -> int:
    try:
        config = json.loads(resources["prettier-source"])
        print_width = config["printWidth"]
    except (KeyError, TypeError, json.JSONDecodeError) as exc:
        raise ValueError("prettier resource must declare printWidth") from exc
    if not isinstance(print_width, int) or isinstance(print_width, bool) or print_width < 1:
        raise ValueError("prettier resource must declare a positive printWidth")
    return print_width


def _caller_input_lines(name: str, values: Sequence[str], *, print_width: int) -> list[str]:
    scalar = _yaml_scalar("\n".join(values))
    prefix = f"      {name}: "
    if not any('"' in value for value in values) and len(prefix) + len(scalar) <= print_width:
        return [f"{prefix}{scalar}"]
    return [f"      {name}: |-", *(f"        {value}" for value in values)]


def _runner_label(value: object, *, name: str) -> str:
    if (
        not isinstance(value, str)
        or not value
        or not (value[0].isascii() and value[0].isalnum())
        or not all(
            character.isascii() and (character.isalnum() or character in "._-")
            for character in value
        )
    ):
        raise ValueError(f"{name} must contain safe runner labels")
    return value


# Issue #132: a managed caller can select the caller's own runner pool. The value
# crosses the workflow_call boundary as a JSON-array *string*, because a reusable
# workflow input cannot be typed as a sequence; the callee re-reads it with
# `fromJSON(inputs.runner-labels)`. Deliberately NOT routed through
# `_caller_input_lines`, which emits its key unconditionally and newline-joins its
# values: an unset or empty `runner_labels` must leave the render byte-identical to
# 1.13's, so the entry is omitted entirely rather than emitted empty. The label
# alphabet enforced above is what makes the single-quoted YAML scalar exact — no
# label can carry a quote or backslash that would need escaping.
def _runner_labels_lines(config: Mapping[str, object]) -> list[str]:
    raw = config.get("runner_labels")
    if raw is None:
        return []
    labels = [
        _runner_label(value, name="config.runner_labels")
        for value in _sequence(raw, name="config.runner_labels")
    ]
    if not labels:
        return []
    return [f"      runner-labels: '{json.dumps(labels, separators=(',', ':'))}'"]


def _lint_caller(config: Mapping[str, object], *, print_width: int) -> str:
    globs = _lint_selection(config)
    lines = ["name: Lint Markdown", "", *_triggers(_automatic(config, "lint")), "", "jobs:"]
    lines.extend(
        [
            "  lint-markdown:",
            "    permissions:",
            "      contents: read",
            "    uses: L3DigitalNet/project-standards/.github/workflows/lint-markdown.yml@v5",
            "    with:",
            f"      markdownlint: {'true' if config.get('lint') is True else 'false'}",
        ]
    )
    lines.extend(_caller_input_lines("globs", globs, print_width=print_width))
    lines.extend(_runner_labels_lines(config))
    return "\n".join(lines) + "\n"


def _format_caller(config: Mapping[str, object], *, print_width: int) -> str:
    globs = _format_selection(config)
    exclusions = _exclusion_globs(config, "format")
    lines = ["name: Format", "", *_triggers(_automatic(config, "format")), "", "jobs:"]
    lines.extend(
        [
            "  format:",
            "    permissions:",
            "      contents: read",
            "    uses: L3DigitalNet/project-standards/.github/workflows/format.yml@v5",
            "    with:",
            f"      prettier: {'true' if config.get('format') is True else 'false'}",
        ]
    )
    lines.extend(_caller_input_lines("globs", globs, print_width=print_width))
    lines.extend(_caller_input_lines("exclusions", exclusions, print_width=print_width))
    lines.extend(_runner_labels_lines(config))
    return "\n".join(lines) + "\n"


def run_render_lint(
    request: Mapping[str, object],
    resources: Mapping[str, bytes],
) -> dict[str, str]:
    """Render the managed lint caller for its selected enforcement state."""
    config = _config(request)
    if config.get("workflow_mode") == "self-hosted":
        return {"content": resources["self-host-lint-workflow"].decode()}
    return {
        "content": _lint_caller(
            config,
            print_width=_prettier_print_width(resources),
        )
    }


def run_render_format(
    request: Mapping[str, object],
    resources: Mapping[str, bytes],
) -> dict[str, str]:
    """Render the managed formatter caller for its selected enforcement state."""
    config = _config(request)
    if config.get("workflow_mode") == "self-hosted":
        return {"content": resources["self-host-format-workflow"].decode()}
    return {
        "content": _format_caller(
            config,
            print_width=_prettier_print_width(resources),
        )
    }


_EDITORCONFIG_VALUES = {
    "property:$global#root": "true",
    "property:*#charset": "utf-8",
    "property:*#end_of_line": "lf",
    "property:*#indent_size": "2",
    "property:*#indent_style": "tab",
    "property:*#insert_final_newline": "true",
    "property:*#trim_trailing_whitespace": "true",
    "property:*.md#indent_size": "2",
    "property:*.md#indent_style": "space",
    "property:*.md#trim_trailing_whitespace": "false",
    "property:*.{yml,yaml}#indent_size": "2",
    "property:*.{yml,yaml}#indent_style": "space",
}

_JSON_VALUES: dict[str, object] = {
    "key:/[json]/editor.defaultFormatter": "esbenp.prettier-vscode",
    "key:/[jsonc]/editor.defaultFormatter": "esbenp.prettier-vscode",
    "key:/[markdown]/editor.defaultFormatter": "esbenp.prettier-vscode",
    "key:/[markdown]/editor.formatOnSave": True,
    "key:/[yaml]/editor.defaultFormatter": "esbenp.prettier-vscode",
    "set:/recommendations#value=DavidAnson.vscode-markdownlint": ("DavidAnson.vscode-markdownlint"),
    "set:/recommendations#value=esbenp.prettier-vscode": "esbenp.prettier-vscode",
}


def _shell_word(value: str) -> str:
    """Quote one glob for POSIX `sh` so no wildcard reaches the shell.

    The option schema already rejects backticks, control characters, a leading
    `!`, and edge whitespace, but it permits an apostrophe, so the `'\\''` escape
    is load-bearing rather than defensive.
    """
    return "'" + value.replace("'", "'\\''") + "'"


def _pathspec(value: str) -> str:
    """Turn one selection entry into the equivalent Git pathspec.

    A selection entry is either a positive glob or a `!`-prefixed negation, and
    both halves must survive the translation or the tracked-file recipes would
    silently lint or format a scope the caller workflow excludes. `exclude` magic
    is Git's own negation, applied after the positive pathspecs regardless of
    argument order, so the ordering `_lint_selection` guarantees for
    markdownlint-cli2 is preserved rather than depended upon here.
    """
    if value.startswith("!"):
        return f":(glob,exclude){value.removeprefix('!')}"
    return f":(glob){value}"


def _tracked_files(selection: Sequence[str]) -> str:
    """Render the `git ls-files` half shared by both local recipes."""
    pathspecs = " ".join(_shell_word(_pathspec(value)) for value in selection)
    return f"git ls-files -z -- {pathspecs}"


def _local_lint_command(config: Mapping[str, object]) -> str:
    """Render the bounded local markdownlint command.

    Issue #114: `markdownlint-cli2 "**/*.md"` recursively descends into
    independent Git repositories checked out beneath the working directory, so a
    workspace parent lints thousands of child-owned documents it does not own
    (the report observed 18230 files against 21 tracked). Routing selection
    through `git ls-files` fixes that at the source: a child repository is a
    gitlink in the parent index, so none of its Markdown is ever listed.

    Three details are load-bearing, each verified against the pinned
    markdownlint-cli2 0.23.2:

    * `--no-globs` is mandatory, not defensive. Without it a consumer's
      `.markdownlint-cli2.*` runner config contributes its own `globs`, which
      re-widens the run back across the child repository and reinstates #114.
    * The `:` prefix marks each argument a literal file path. Without it every
      path is parsed as a glob, and a name beginning with `#` or `!` is read as a
      negation and silently dropped from the run.
    * The generated-directory negations the caller workflow needs are not
      repeated here. Nothing is expanded, and `git ls-files` never emits an
      ignored tree; the exclusions still reach Git through `_pathspec`, which
      keeps parity with the rendered caller scope when a consumer tracks one of
      those directories deliberately.

    `sed -z` and `xargs -0 -r` are GNU forms, matching the Prettier recipe.
    """
    return (
        f"{_tracked_files(_lint_selection(config))}"
        " | sed -z 's|^|:|' | xargs -0 -r npx markdownlint-cli2 --no-globs"
    )


def _local_format_commands(config: Mapping[str, object]) -> list[str]:
    """Render the two bounded local Prettier commands, normative form first.

    Issue #88: `prettier --check .` traverses every language Prettier supports and
    every tree Git excludes, so the documented local check both exceeded the
    declared corpus and could fail on consumer scratch that CI never sees.

    The normative form makes Git the corpus authority. `git ls-files` honors
    `.gitignore` at every level *and* `.git/info/exclude`, and lists nothing from
    an independent nested repository, none of which Prettier's own selection can
    do: Prettier reads only the working-directory `.gitignore`/`.prettierignore`.
    Passing `.git/info/exclude` through `--ignore-path` was rejected because
    Prettier anchors an ignore file's patterns to that file's own directory, so
    every pattern would resolve against `.git/info/`.

    `:(glob)` magic is required, not decorative. Under default pathspec magic
    `**/*.md` skips root-level files and `nested/**/*.md` matches nothing at all;
    `:(glob)` selects wildmatch, whose `**/` means "zero or more leading
    directories" — the same reading Prettier gives the configured glob.

    `xargs -r` suppresses the run on an empty set, and an unmatched pathspec is
    not an error, so a repository lacking one configured type (`**/*.jsonc` is the
    common case) cannot produce a spurious failure. The fallback needs
    `--no-error-on-unmatched-pattern` to reach the same outcome, because Prettier
    exits 2 on a pattern that matches nothing.

    One consequence a consumer scripting this must know: `xargs` maps any child
    status in 1..125 onto 123, so the normative form cannot re-emit Prettier's own
    1-means-findings / 2-means-error distinction. Zero still means clean and
    non-zero still means "attend to this"; read the output to tell them apart.

    The two forms differ in one more way, and the guide has to say so: only the
    Git-routed form applies typed `format`/`both` exclusions, because Git can
    express negation in the same selection and Prettier's CLI cannot. A consumer
    with declared format exclusions who falls back must add `--ignore-path`.
    """
    globbed = " ".join(_shell_word(glob) for glob in _format_selection(config))
    return [
        f"{_tracked_files(_format_local_selection(config))} | xargs -0 -r npx prettier --check --",
        f"npx prettier --check --no-error-on-unmatched-pattern -- {globbed}",
    ]


def _instructions(config: Mapping[str, object]) -> str:
    enabled = [tool for tool in ("format", "lint") if config.get(tool) is True]
    markdown_globs = _globs(config, "markdown_globs")
    config_globs = _globs(config, "config_globs")
    lines = [
        "<!-- markdownlint-disable MD025 -->",
        "# Markdown and structured-text tooling",
        "",
        "Prettier owns physical formatting and markdownlint owns Markdown structure. Do not add overlapping tools.",
        "",
        f"Enabled checks: {', '.join(enabled) if enabled else 'none'}.",
        f"Markdown scope: {', '.join(f'`{item}`' for item in markdown_globs)}.",
        f"Structured-config scope: {', '.join(f'`{item}`' for item in config_globs)}.",
    ]
    # The lint scope an agent reads here must match the scope the caller renders,
    # or the instruction block understates what CI actually skips (issue #63).
    defaults = _default_lint_exclusions(config, _exclusion_globs(config, "lint"))
    if config.get("lint") is True and defaults:
        lines.append(
            "Lint additionally skips generated directories: "
            f"{', '.join(f'`{item}`' for item in defaults)}."
        )
    exclusions = _sequence(config.get("exclusions"), name="config.exclusions")
    if exclusions:
        lines.extend(["", "Declared exclusions:"])
        for raw in exclusions:
            exclusion = _table(raw, name="config.exclusions item")
            lines.append(
                f"- `{exclusion.get('glob')}` ({exclusion.get('applies_to')}): "
                f"{exclusion.get('reason')}"
            )
    if config.get("format") is True:
        # The block is the only place an agent reads the selected scope, so the
        # runnable command belongs beside it; anywhere else it drifts from the
        # globs above. Blank lines and the `bash` tag keep MD031/MD040 satisfied
        # even though the surrounding prettier-ignore range exempts the fence from
        # Prettier, not from markdownlint.
        tracked, globbed = _local_format_commands(config)
        fallback_caveat = (
            "Without Git, bound the same scope by glob instead. Prettier's CLI has no "
            "negative pattern, so this form does not apply the declared format "
            "exclusions above; pass them through an `--ignore-path` file inside the "
            "repository:"
            if _exclusion_globs(config, "format")
            else "Without Git, bound the same scope by glob instead:"
        )
        lines.extend(
            [
                "",
                "Check formatting over exactly that scope, with Git as the corpus authority:",
                "",
                "```bash",
                tracked,
                "```",
                "",
                fallback_caveat,
                "",
                "```bash",
                globbed,
                "```",
                "",
                "Never check or write with a bare `.`: it reaches undeclared languages and "
                "Git-excluded scratch.",
            ]
        )
    if config.get("lint") is True:
        lines.extend(
            [
                "",
                "Lint Markdown structure over the same Git-tracked scope:",
                "",
                "```bash",
                _local_lint_command(config),
                "```",
                "",
                "Never lint a bare recursive glob: it descends into any independent Git "
                "repository checked out below this one.",
            ]
        )
    lines.extend(
        [
            "",
            "Run the enabled checks before claiming completion.",
            "<!-- markdownlint-enable MD025 -->",
        ]
    )
    return "\n".join(lines) + "\n"


def run_render_semantic(
    request: Mapping[str, object],
    _resources: Mapping[str, bytes],
) -> dict[str, str]:
    """Render one declared shared-container unit without reading live files."""
    snapshots = _table(request.get("snapshots"), name="snapshots")
    planned = _table(
        snapshots.get("planned_contribution"),
        name="snapshots.planned_contribution",
    )
    adapter = planned.get("adapter")
    scope = planned.get("scope")
    if adapter == "editorconfig" and isinstance(scope, str):
        try:
            value = _EDITORCONFIG_VALUES[scope]
        except KeyError as exc:
            raise ValueError("undeclared EditorConfig contribution scope") from exc
        section, key = scope.removeprefix("property:").rsplit("#", 1)
        if section == "$global":
            return {"content": f"{key} = {value}\n"}
        return {"content": f"[{section}]\n{key} = {value}\n"}
    if adapter == "jsonc" and isinstance(scope, str):
        try:
            value = _JSON_VALUES[scope]
        except KeyError as exc:
            raise ValueError("undeclared JSONC contribution scope") from exc
        if scope.startswith("key:/"):
            content: object = value
            for key in reversed(scope.removeprefix("key:/").split("/")):
                content = {key: content}
        else:
            content = {"recommendations": [value]}
        return {"content": json.dumps(content, separators=(",", ":"))}
    if adapter == "markdown-block" and scope == "block:markdown-tooling":
        body = _instructions(_config(request))
        return {
            "content": (
                "<!-- prettier-ignore-start -->\n\n"
                "<!-- BEGIN project-standards:markdown-tooling -->\n"
                f"{body}"
                "<!-- END project-standards:markdown-tooling -->\n\n"
                "<!-- prettier-ignore-end -->\n"
            )
        }
    raise ValueError("unsupported Markdown Tooling semantic contribution")


def _digest(content: bytes) -> str:
    return f"sha256:{hashlib.sha256(content).hexdigest()}"


def _finding(code: str, path: str, identity: str, message: str) -> dict[str, str]:
    return {
        "code": code,
        "severity": "error",
        "path": path,
        "identity": identity,
        "message": message,
        "hint": "reconcile the selected Markdown Tooling payload",
    }


def _verify(
    request: Mapping[str, object],
    resources: Mapping[str, bytes],
    *,
    tool: str,
) -> dict[str, object]:
    config = _config(request)
    if config.get(tool) is not True:
        return {"findings": []}
    snapshots = _table(request.get("snapshots"), name="snapshots")
    if config.get("workflow_mode") == "self-hosted":
        resource_id = f"self-host-{tool}-workflow"
        workflow = f".github/workflows/{'lint-markdown' if tool == 'lint' else 'format'}.yml"
        expected = {workflow: _digest(resources[resource_id])}
        config_path = ".markdownlint.json" if tool == "lint" else ".prettierrc.json"
        source_id = "markdownlint-source" if tool == "lint" else "prettier-source"
        expected[config_path] = _digest(resources[source_id])
    elif tool == "lint":
        expected = {
            ".markdownlint.json": _digest(resources["markdownlint-source"]),
            ".github/workflows/lint-markdown.yml": _digest(
                _lint_caller(
                    config,
                    print_width=_prettier_print_width(resources),
                ).encode()
            ),
        }
    else:
        expected = {
            ".prettierrc.json": _digest(resources["prettier-source"]),
            ".github/workflows/format.yml": _digest(
                _format_caller(
                    config,
                    print_width=_prettier_print_width(resources),
                ).encode()
            ),
        }
    if config.get(f"{tool}_workflow_ownership") == "consumer-owned":
        workflow_name = "lint-markdown" if tool == "lint" else "format"
        expected.pop(f".github/workflows/{workflow_name}.yml", None)
    if tool == "lint" and config.get("markdownlint_config_ownership") == "consumer-owned":
        expected.pop(".markdownlint.json", None)
    findings: list[dict[str, str]] = []
    for path, digest in expected.items():
        observed = snapshots.get(path)
        table = _optional_table(observed)
        if table.get("kind") != "regular" or table.get("content_digest") != digest:
            findings.append(
                _finding(
                    f"MT-{tool.upper()}-DRIFT",
                    path,
                    "$file",
                    f"managed {tool} bytes do not match the selected payload",
                )
            )
    return {"findings": findings}


def run_verify_lint(
    request: Mapping[str, object],
    resources: Mapping[str, bytes],
) -> dict[str, object]:
    """Verify selected lint configuration and caller digests."""
    return _verify(request, resources, tool="lint")


def run_verify_format(
    request: Mapping[str, object],
    resources: Mapping[str, bytes],
) -> dict[str, object]:
    """Verify selected formatter configuration and caller digests."""
    return _verify(request, resources, tool="format")


_SIGNATURES = {
    "legacy-editorconfig": (".editorconfig", "shared", "preserve"),
    "legacy-format-caller": (".github/workflows/format.yml", "managed", "adopt"),
    "legacy-lint-caller": (".github/workflows/lint-markdown.yml", "managed", "adopt"),
    "legacy-markdownlint-config": (".markdownlint.json", "managed", "adopt"),
    "legacy-prettier-config": (".prettierrc.json", "managed", "adopt"),
    "legacy-vscode-extensions": (".vscode/extensions.json", "shared", "preserve"),
}
_SELF_HOST_WORKFLOW_COHORTS: tuple[frozenset[tuple[str, str]], ...] = (
    frozenset(
        {
            (
                "legacy-format-caller",
                "sha256:20849953a584fbb18b8a3a0acab2b1357c23077c226e76bd7a6d580d73a4ce20",
            ),
            (
                "legacy-lint-caller",
                "sha256:89ad3220574ce78a9628208d768344f300e5e1d701d7adaf16eb923f4cc8f772",
            ),
        }
    ),
    frozenset(
        {
            (
                "legacy-format-caller",
                "sha256:6682b88448f4919cba6658cca46dd8c82ea59af2c91823424d03ad26c5a6e2ce",
            ),
            (
                "legacy-lint-caller",
                "sha256:3124debdc76f2c69dce5e24029de4defb424661835ce8ffad45084276782f656",
            ),
        }
    ),
)
_SELF_HOST_WORKFLOW_MEMBERS = frozenset(
    member for cohort in _SELF_HOST_WORKFLOW_COHORTS for member in cohort
)
_WORKFLOW_SIGNATURE_IDS = frozenset({"legacy-format-caller", "legacy-lint-caller"})
_DISABLED_FORMAT_CALLER_DIGESTS = frozenset(
    {"sha256:b7d9816b79e66df79fa02d34bbb01b848a50228d527071a8ec9f566f6da6a9e4"}
)

# Signatures whose targets stay managed only through bounded units in this
# payload; the declarations carry unknown_content_disposition = "preserve", so
# unrecognized bytes become a preserve claim (bounded takeover) instead of a
# blocking MT-LEGACY-MODIFIED finding.
_BOUNDED_TAKEOVER_SIGNATURES = frozenset({"legacy-editorconfig", "legacy-vscode-extensions"})


def run_migrate(
    request: Mapping[str, object],
    _resources: Mapping[str, bytes],
) -> dict[str, object]:
    """Map V4 package metadata and exact artifacts without emitting YAML."""
    snapshots = _table(request.get("snapshots"), name="snapshots")
    legacy = _table(snapshots.get("legacy_config"), name="snapshots.legacy_config")
    namespace = _table(legacy.get("markdown_tooling"), name="legacy_config.markdown_tooling")
    config: dict[str, object] = {}
    recognized: list[str] = []
    if "version" in namespace:
        config["contract_version"] = (
            "1.1" if namespace["version"] == "1.0" else namespace["version"]
        )
        recognized.append("/markdown_tooling/version")
    # Relinquishable caller signatures: the pointed-at per-caller ownership
    # setting lets migration preserve an unrecognized consumer customization
    # instead of blocking on it.
    relinquished: dict[str, str] = {}
    for option, signature_id in (
        ("lint_workflow_ownership", "legacy-lint-caller"),
        ("format_workflow_ownership", "legacy-format-caller"),
        ("markdownlint_config_ownership", "legacy-markdownlint-config"),
    ):
        if option in namespace:
            config[option] = namespace[option]
            recognized.append(f"/markdown_tooling/{option}")
            if namespace[option] == "consumer-owned":
                relinquished[signature_id] = f"/markdown_tooling/{option}"

    signatures = _table(
        snapshots.get("legacy_signatures"),
        name="snapshots.legacy_signatures",
    )
    claims: list[dict[str, object]] = []
    findings: list[dict[str, str]] = []
    workflow_observations: set[tuple[str, str]] = set()
    for signature_id, (target, ownership, disposition) in _SIGNATURES.items():
        raw_signature = signatures.get(signature_id)
        if not isinstance(raw_signature, Mapping):
            continue
        observed = cast("Mapping[str, object]", raw_signature).get(target)
        if not isinstance(observed, Mapping):
            continue
        state = cast("Mapping[str, object]", observed)
        digest = state.get("digest")
        relinquish = signature_id in relinquished
        if state.get("known") is True and isinstance(digest, str):
            if signature_id in _WORKFLOW_SIGNATURE_IDS:
                workflow_observations.add((signature_id, digest))
            if signature_id == "legacy-format-caller" and digest in (
                _DISABLED_FORMAT_CALLER_DIGESTS
            ):
                config["format"] = False
                config["ci"] = {"format_caller": False}
            claims.append(
                {
                    "signature_id": signature_id,
                    "target": target,
                    "observed_digest": digest,
                    "ownership": "consumer-owned" if relinquish else ownership,
                    "disposition": "preserve" if relinquish else disposition,
                }
            )
        elif relinquish and isinstance(digest, str):
            claims.append(
                {
                    "signature_id": signature_id,
                    "target": target,
                    "observed_digest": digest,
                    "ownership": "consumer-owned",
                    "disposition": "preserve",
                    "intent_pointer": relinquished[signature_id],
                }
            )
        elif signature_id in _BOUNDED_TAKEOVER_SIGNATURES and isinstance(digest, str):
            claims.append(
                {
                    "signature_id": signature_id,
                    "target": target,
                    "observed_digest": digest,
                    "ownership": ownership,
                    "disposition": "preserve",
                }
            )
        elif isinstance(digest, str):
            findings.append(
                {
                    "code": "MT-LEGACY-MODIFIED",
                    "severity": "error",
                    "path": target,
                    "identity": signature_id,
                }
            )
    # Relinquished workflows carry no mode evidence: the package stops managing
    # them, so a partially recognized self-hosted pair must not block migration.
    if not (_WORKFLOW_SIGNATURE_IDS & relinquished.keys()):
        observed_workflow_cohort = frozenset(workflow_observations)
        if observed_workflow_cohort in _SELF_HOST_WORKFLOW_COHORTS:
            config["workflow_mode"] = "self-hosted"
        elif observed_workflow_cohort & _SELF_HOST_WORKFLOW_MEMBERS:
            findings.append(
                {
                    "code": "MT-LEGACY-WORKFLOW-MODE",
                    "severity": "error",
                    "path": ".github/workflows",
                    "identity": "self-hosted-pair",
                }
            )
    claims.sort(key=lambda item: str(item["signature_id"]).encode())
    findings.sort(key=lambda item: (item["path"].encode(), item["identity"].encode()))
    return {
        "schema_version": "1.0",
        "package": {
            "standard_id": "markdown-tooling",
            "version": str(request.get("version")),
            "selector": "latest",
            "config": config,
            "recognized_settings": recognized,
        },
        "claims": claims,
        "findings": findings,
    }
