"""Enumerate a payload or repository tree the way the package contract sees it.

Interpreter-generated bytecode is not repository content, and no test may treat it
as such. Importing a payload provider — every `standards/<family>/versions/<v>/
providers/*.py`, reached at runtime through the `src/project_standards/payloads`
symlink projection — makes CPython write `providers/__pycache__/*.pyc` beside the
source. The self-hosted CI runner reuses its workspace between runs, so those
caches survive into the next checkout's test session and a test that enumerates
the source tree then sees a file the payload never declared. That failure mode
took hosted `Check` red on `main` for four consecutive runs (1a01038d onward),
always as a set or mapping comparison against declared, projected, or wheel
content.

Bytecode can never be payload content on the other side of any such comparison:
`validate_payload_integrity` skips `__pycache__` directories and `.pyc` files when
it inventories a payload (see `_live_files` in
`src/project_standards/package_contract/integrity.py`, which owns the canonical
rule this module mirrors); the projection is planned from that inventory, so no
cache is ever linked; and the uv build backend's default excludes keep
`__pycache__` out of the built wheel. Deleting caches before a run is a
workaround — the enumeration itself has to agree with the inventory rule.

Cross-file contract: when the integrity inventory's exclusion changes, this
module changes with it, or the tests stop describing the shipped package.
"""

from __future__ import annotations

from pathlib import Path

_CACHE_DIRECTORY = "__pycache__"
_BYTECODE_SUFFIXES = frozenset({".pyc", ".pyo"})


def is_bytecode_artifact(path: Path, *, root: Path | None = None) -> bool:
    """Report whether `path` is interpreter-written bytecode rather than content.

    A `__pycache__` directory and the compiled files inside it both qualify. When
    `root` is given only the part of the path below it is inspected, so a scratch
    directory that itself sits under some `__pycache__` ancestor is still walked
    normally.
    """
    relative = path.relative_to(root) if root is not None else path
    if _CACHE_DIRECTORY in relative.parts:
        return True
    return path.suffix in _BYTECODE_SUFFIXES


def payload_tree(root: Path, pattern: str = "*") -> tuple[Path, ...]:
    """Return every path under `root` matching `pattern`, minus bytecode caches.

    Sorted so callers comparing two trees, or asserting on a first element, do not
    depend on directory order. Returns an empty tuple for a missing `root` rather
    than raising, matching `Path.rglob`'s behaviour on a nonexistent directory.
    """
    return tuple(
        sorted(path for path in root.rglob(pattern) if not is_bytecode_artifact(path, root=root))
    )
