#!/usr/bin/env bash
# Install this repository's tracked Git hooks into the common Git directory.
#
# Durability is the whole point (ledger 20): .git/hooks is untracked, so a
# guard that lives only there dies with the next clone or worktree. The tracked
# source under scripts/githooks/ is the single authority, and what lands in
# .git/hooks is a generated adapter that execs it — editing the installed copy
# is therefore never the way to change behaviour. `scripts/bootstrap-worktree.sh`
# runs this on every fresh checkout, which is what makes the guard reappear.
#
# Usage: scripts/install-githooks.sh
#
# Requirements: bash, git, coreutils (mktemp, mv, chmod). Deliberately no
# Python and no project virtualenv: bootstrap runs this before `uv sync`, and a
# hook installer that needs the environment it precedes cannot be trusted.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly MANAGED_MARKER='# project-standards-managed-hook: v1'
readonly BACKUP_SUFFIX='.project-standards-original'
readonly GUARD_RELATIVE_PATH='scripts/githooks/main-branch-guard'

# Both roles of the same tracked guard; see its header for why the pair is
# required rather than either hook alone.
readonly MANAGED_HOOKS=(pre-commit commit-msg)

die() {
    printf 'install-githooks: %s\n' "$1" >&2
    exit 1
}

is_managed_adapter() {
    [[ -f "$1" ]] && grep -Fqx "$MANAGED_MARKER" "$1"
}

write_adapter() {
    local hook_name="$1" hook_path="$2" predecessor="$3" temporary_path
    temporary_path="$(mktemp "$(dirname "$hook_path")/.${hook_name}.project-standards.XXXXXX")"

    # The single-quoted lines are emitted literally into the generated adapter.
    # shellcheck disable=SC2016
    printf '%s\n' \
        '#!/usr/bin/env bash' \
        "$MANAGED_MARKER" \
        '# Generated by scripts/install-githooks.sh. Edit the tracked source, not this file.' \
        'set -euo pipefail' \
        "predecessor=$(printf '%q' "$predecessor")" \
        'if [[ -x "$predecessor" ]]; then' \
        '  "$predecessor" "$@"' \
        'fi' \
        '# Prefer the invoking worktree'"'"'s own checkout so the guard a commit is' \
        '# judged by is the one that commit can see; fall back to the install-time' \
        '# root for a worktree whose branch predates the tracked guard.' \
        'toplevel="$(git rev-parse --show-toplevel 2>/dev/null || true)"' \
        "guard=\"\${toplevel:-}/$GUARD_RELATIVE_PATH\"" \
        "fallback=$(printf '%q' "$REPO_ROOT/$GUARD_RELATIVE_PATH")" \
        '[[ -x "$guard" ]] || guard="$fallback"' \
        'if [[ ! -x "$guard" ]]; then' \
        '  # Fail closed on main only: a missing guard must not silently reopen' \
        '  # the branch it protects, and must not block work on every other branch.' \
        '  branch="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"' \
        '  if [[ "$branch" == "main" ]]; then' \
        '    printf "project-standards hook: guard missing (%s); refusing to commit on main.\n" "$guard" >&2' \
        '    exit 1' \
        '  fi' \
        '  exit 0' \
        'fi' \
        "exec \"\$guard\" $hook_name \"\$@\"" \
        >"$temporary_path"
    chmod 755 "$temporary_path"
    # Rename within the same directory: an interrupted install leaves either the
    # old hook or the new one, never a half-written executable hook.
    mv -f -- "$temporary_path" "$hook_path"
}

[[ -x "$REPO_ROOT/$GUARD_RELATIVE_PATH" ]] ||
    die "missing executable guard source: $REPO_ROOT/$GUARD_RELATIVE_PATH"
git -C "$REPO_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1 ||
    die 'run inside the target repository.'

# The common directory, not --git-dir: a linked worktree has its own git-dir but
# shares the common repository's hooks directory, so installing from a worktree
# must (and does) reach the primary checkout's .git/hooks.
git_common_dir="$(cd "$REPO_ROOT" && cd "$(git rev-parse --git-common-dir)" && pwd)"
hooks_dir="$git_common_dir/hooks"
mkdir -p -- "$hooks_dir" || die "cannot create $hooks_dir"
[[ -w "$hooks_dir" ]] || die "hook directory is not writable: $hooks_dir"

for hook_name in "${MANAGED_HOOKS[@]}"; do
    hook_path="$hooks_dir/$hook_name"
    backup_path="$hook_path$BACKUP_SUFFIX"

    if [[ -e "$hook_path" ]] && ! is_managed_adapter "$hook_path"; then
        # Refuse rather than overwrite: a second unmanaged predecessor means the
        # first backup would be destroyed, and with it the only copy of a hook
        # this installer did not write.
        [[ ! -e "$backup_path" ]] ||
            die "refusing to replace $hook_path: predecessor backup already exists at $backup_path"
        mv -- "$hook_path" "$backup_path"
        printf 'install-githooks: preserved predecessor %s -> %s\n' "$hook_path" "$backup_path"
    fi

    write_adapter "$hook_name" "$hook_path" "$backup_path"
    printf 'install-githooks: installed %s -> %s\n' "$hook_path" "$REPO_ROOT/$GUARD_RELATIVE_PATH"
done
