package render

import (
	"fmt"
	"strings"
)

// Section headings, fixed and shared by both markdown surfaces. They are the anchors the
// ledger's table of contents links to, so changing one changes the contract.
const (
	sectionAttention = "Needs attention"
	sectionIssues    = "Issues"
	sectionPulls     = "Pull requests"
	sectionFollowUps = "Discovered follow-ups"
	sectionContents  = "Contents"
)

// The empty-section lines. A section with nothing in it says so in one line rather than
// disappearing: a layout whose shape depends on the data is not comparable across reads.
const (
	noAttention = "Nothing needs attention: no blocked, underspecified, out-of-sync, or overdue work."
	noIssues    = "No open issues."
	noPulls     = "No open pull requests."
	// The tool reports live GitHub state; noticing durable follow-up work while
	// summarizing is the agent's job, and this tail is where the agent adds it.
	noFollowUps = "No follow-ups recorded: the tool reports live GitHub state and does not discover work."
)

var (
	issueColumns = []string{"Issue", "Type", "Title", "Workflow", "Priority", "Size / Severity", "Execution mode"}
	pullColumns  = []string{"PR", "Title", "Governing issue", "State", "CI", "Risk notes"}
)

type section struct {
	heading string
	body    string
}

// Summary renders the operator summary: attention first, then the inventories, then the
// follow-ups tail. It is a read and prints to stdout for the agent to relay verbatim.
func Summary(s *Snapshot) string {
	return document(s, []string{"Read " + s.scopeLine()}, false)
}

// Ledger renders the generated consumer file: the same layout, preceded by the
// generated-file header (timestamp, tool version, do-not-edit notice) and a table of
// contents linking every section (spec FR-019).
func Ledger(s *Snapshot) string {
	return document(s, []string{
		fmt.Sprintf("Generated by `gh-workflow` %s · read %s", Version, s.scopeLine()),
		"Do not edit: `gh-workflow ledger` regenerates this file in whole, and manual edits are overwritten.",
	}, true)
}

// scopeLine is the timestamp and the counts the tables below cover.
func (s *Snapshot) scopeLine() string {
	return fmt.Sprintf("%s · %s · %s",
		s.Timestamp(),
		plural(len(s.Issues), "open issue", "open issues"),
		plural(len(s.PullRequests), "open PR", "open PRs"))
}

func document(s *Snapshot, header []string, contents bool) string {
	sections := []section{
		{sectionAttention, attentionBody(s)},
		{sectionIssues, issuesBody(s)},
		{sectionPulls, pullsBody(s)},
		{sectionFollowUps, noFollowUps + "\n"},
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s — work state\n", s.Target)
	for _, line := range header {
		fmt.Fprintf(&b, "\n%s\n", line)
	}
	if contents {
		fmt.Fprintf(&b, "\n## %s\n\n", sectionContents)
		for _, sec := range sections {
			fmt.Fprintf(&b, "- [%s](#%s)\n", sec.heading, Anchor(sec.heading))
		}
	}
	for _, sec := range sections {
		fmt.Fprintf(&b, "\n## %s\n\n%s", sec.heading, sec.body)
	}
	return b.String()
}

func attentionBody(s *Snapshot) string {
	findings := s.Attention()
	if len(findings) == 0 {
		return noAttention + "\n"
	}
	var b strings.Builder
	for _, finding := range findings {
		fmt.Fprintf(&b, "- **%s** — #%d %s: %s\n",
			finding.Category, finding.Number, EscapeText(finding.Title), EscapeText(finding.Detail))
	}
	return b.String()
}

func issuesBody(s *Snapshot) string {
	if len(s.Issues) == 0 {
		return noIssues + "\n"
	}
	rows := make([][]string, 0, len(s.Issues))
	for _, issue := range s.Issues {
		rows = append(rows, []string{
			fmt.Sprintf("#%d", issue.Number),
			orDash(issue.Type),
			issue.Title,
			orDash(issue.Field(FieldWorkflow)),
			orDash(issue.Field(FieldPriority)),
			orDash(issue.SizeOrSeverity()),
			orDash(issue.Field(FieldExecutionMode)),
		})
	}
	return Table(issueColumns, rows)
}

func pullsBody(s *Snapshot) string {
	if len(s.PullRequests) == 0 {
		return noPulls + "\n"
	}
	rows := make([][]string, 0, len(s.PullRequests))
	for _, pull := range s.PullRequests {
		governing := dash
		if pull.GoverningIssue != 0 {
			governing = fmt.Sprintf("#%d", pull.GoverningIssue)
		}
		rows = append(rows, []string{
			fmt.Sprintf("#%d", pull.Number),
			pull.Title,
			governing,
			orDash(pull.StateLabel()),
			orDash(pull.CI),
			orDash(pull.RiskNotes),
		})
	}
	return Table(pullColumns, rows)
}

func plural(count int, singular, many string) string {
	if count == 1 {
		return fmt.Sprintf("%d %s", count, singular)
	}
	return fmt.Sprintf("%d %s", count, many)
}
